version: 2
enable-beta-ecosystems: true
updates:
  # Daily: Major updates and security updates
  - package-ecosystem: "uv"
    target-branch: "main" # Workaround to allow multiple schedules. see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"

  # Monthly: Bundle patch updates together
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase-if-necessary
    groups:
      patch-updates:
        update-types:
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"

  # Daily: GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
