version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
