version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install uv
      - uv pip install .
      - uv pip install sphinx-rtd-theme

sphinx:
  configuration: docs/conf.py
