version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - poetry config virtualenvs.create false
      - poetry install --with doc

sphinx:
  configuration: docs/conf.py
